version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
artifacts:
    files:
      - '**/*'