# Generated by Django 2.0.2 on 2023-04-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='author',
            new_name='user',
        ),
    ]
